package controller;

public enum MenuCommands {
	APP_QUIT, SHOW_LIST_WAREHOUSE, SHOW_DETAIL_WAREHOUSE, SHOW_ADD_WAREHOUSE, SHOW_LIST_PARTS, SHOW_DETAIL_PART, SHOW_ADD_PART, DELETE_PART, DELETE_WAREHOUSE,
	SHOW_LIST_INVENTORY, SHOW_DETAIL_INVENTORY, ADD_INVENTORY, DELETE_INVENTORY, LOGIN_AS_BOB_ROBERTS, LOGIN_AS_SUE_WILLIAMS, LOGIN_AS_RAGNAR_JONES, LOGIN_AS_GRACE_KELLY, LOGOUT,
	WAREHOUSE_INVENTORY_REPORT_PDF, WAREHOUSE_INVENTORY_REPORT_EXCEL


}
